"""create TokenBlocklist model

Revision ID: d28085822488
Revises: 52269bfde792
Create Date: 2024-02-15 20:15:54.517804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28085822488'
down_revision = '52269bfde792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
